// Custom Worker entry that wraps OpenNext's generated worker.
// Routes /h/{id}[/...] and /s/{id} to the WebhookSession Durable Object;
// everything else falls through to the Next.js app.

// The Next.js worker is generated by `opennextjs-cloudflare build`. The file
// may be absent on a fresh checkout, so we suppress the resolution error rather
// than relying on `@ts-expect-error`, which itself errors once the file exists.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import openNextHandler from "./.open-next/worker.js";

export { WebhookSession } from "./src/lib/webhook-session";

const HOOK_RE = /^\/h\/([A-Za-z0-9_-]{8,64})(\/.*)?$/;
const STREAM_RE = /^\/s\/([A-Za-z0-9_-]{8,64})$/;

const handler: ExportedHandler<CloudflareEnv> = {
	async fetch(request, env, ctx) {
		const url = new URL(request.url);

		const hookMatch = url.pathname.match(HOOK_RE);
		if (hookMatch) {
			const [, id, rest] = hookMatch;
			const stub = env.WEBHOOK_SESSION.get(env.WEBHOOK_SESSION.idFromName(id));
			const forward = new URL(request.url);
			forward.pathname = "/webhook" + (rest ?? "");
			return stub.fetch(new Request(forward.toString(), request));
		}

		const streamMatch = url.pathname.match(STREAM_RE);
		if (streamMatch) {
			const [, id] = streamMatch;
			const stub = env.WEBHOOK_SESSION.get(env.WEBHOOK_SESSION.idFromName(id));
			const forward = new URL(request.url);
			forward.pathname = "/stream";
			return stub.fetch(new Request(forward.toString(), request));
		}

		return (openNextHandler as ExportedHandler<CloudflareEnv>).fetch!(
			request,
			env,
			ctx,
		);
	},
};

export default handler;
